PACKAGE_NAME="schenker-kbd"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="schenker_kbd"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_ARCH="^x86_64$"
